### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by jimanvlad** [clarkdave/DSACancellationChecker#2]
Hi,

I seem to get this error half of the time: 

[2013-06-03 @ 07:09]
---> Starting update...
---> Connecting to https://driverpracticaltest.direct.gov.uk/login

---> Connecting to https://driverpracticaltest.direct.gov.uk/login
-----> Sending data:
-------> username = XX
-------> password = XX
Traceback (most recent call last):
  File "/XX/DSACancellationChecker-master/DSAChecker.py", line 185, in <module>
    performUpdate()
  File "/XX/DSACancellationChecker-master/DSAChecker.py", line 144, in performUpdate
    dateChangeURL = launcher.html.find(id="date-time-change").get('href')
AttributeError: 'NoneType' object has no attribute 'get'

Any idea?

Also, any plans to add automatic booking? ^_^

**Comment by felipe-vvoosh** [comment]
I put the right value in the field but still got this issue...
