### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by rayic3** [clarkdave/DSACancellationChecker#8]
Hi I am getting the same Attribute issue. Any suggestions on how to fix. Screenshot attached. I have redacted the username and password for obvious reasons, but I had them filled before I ran. 

![2016-09-26](https://cloud.githubusercontent.com/assets/19370810/18842267/5d333e7c-840c-11e6-9a6c-bc78223af72d.png)

**Comment by goodoldme** [comment]
The service is available only between 6am and 11;30pm. You'd get this error if you try to access DVSA site any other time. Hope this helps

**Comment by goodoldme** [comment]
Closing the issue as this occurs when service is down
